from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from .ids import class_suffix


def _config_class(item: dict, prefix: str) -> str:
    return item.get("dayz_class") or prefix + class_suffix(item["name"], item["code"])


def _enforce_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _action_class(item: dict) -> str:
    return f'ActionPaintZPaint_{item["type_code"]}_{item["id"]}'


def _scale_percent(scale: float) -> int:
    percent = round(float(scale) * 100)
    if percent <= 0 or percent > 1000:
        raise ValueError(f"Invalid PaintZ pattern scale: {scale!r}")
    if abs(float(scale) - percent / 100.0) > 1e-9:
        raise ValueError(f"PaintZ pattern scale must resolve to a whole percentage: {scale!r}")
    return percent


def emit_dayz(catalog: list[dict], dayz: dict, out_dir: Path, pattern_scales: list[float] | None = None):
    out_dir.mkdir(parents=True, exist_ok=True)
    if not dayz.get("emit_config_fragment", True):
        return

    base = dayz.get("base_class", "PaintZ_SprayCanBase")
    prefix = dayz.get("class_prefix", "PaintZ_SprayCan_")
    root = dayz.get("texture_root", r"PaintZ\data\cans").rstrip("\\")
    prop = dayz.get("texture_assignment", "hiddenSelectionsTextures")
    repeat = int(dayz.get("hidden_selection_repeat", 1))
    if repeat < 1:
        raise ValueError("dayz.hidden_selection_repeat must be at least 1")

    pattern_scales = pattern_scales or [1.0]
    supported_scale_percents: list[int] = []
    seen_scale_percents: set[int] = set()
    for scale in pattern_scales:
        percent = _scale_percent(scale)
        if percent in seen_scale_percents:
            raise ValueError(f"Duplicate PaintZ pattern scale: {scale!r}")
        seen_scale_percents.add(percent)
        supported_scale_percents.append(percent)
    if 100 not in seen_scale_percents:
        raise ValueError("PaintZ pattern scales must include 1.0")

    config_classes: set[str] = set()
    action_classes: set[str] = set()
    for item in catalog:
        config_class = _config_class(item, prefix)
        action_class = _action_class(item)
        if config_class in config_classes:
            raise ValueError(f"Duplicate generated DayZ classname: {config_class}")
        if action_class in action_classes:
            raise ValueError(f"Duplicate generated PaintZ action classname: {action_class}")
        config_classes.add(config_class)
        action_classes.add(action_class)

    config_lines = [
        "// AUTO-GENERATED by PaintZ PackKit. DO NOT EDIT.",
        "// Finish metadata and can artwork are generated from the pack manifest.",
    ]
    for item in catalog:
        config_class = _config_class(item, prefix)
        texture = root + "\\" + item["texture_stem"] + "_co.paa"
        values = ", ".join(f'"{texture}"' for _ in range(repeat))
        config_lines += [
            f"class {config_class}: {base}",
            "{",
            "    scope = 2;",
            f'    displayName = "PaintZ {item["name"]}";',
            f'    descriptionShort = "{item["code"]} - PaintZ {item["type"]} spray coating";',
            f'    paintzCode = "{item["code"]}";',
            f'    paintzType = "{item["type"]}";',
            f"    {prop}[] = {{{values}}};",
            "};",
            "",
        ]
    (out_dir / "PaintZ_Paints.generated.inc").write_text("\n".join(config_lines), encoding="utf-8")

    unit_lines = ["// AUTO-GENERATED by PaintZ PackKit. DO NOT EDIT."]
    unit_lines.extend(f'"{_config_class(item, prefix)}",' for item in catalog)
    (out_dir / "PaintZ_Units.generated.inc").write_text("\n".join(unit_lines) + "\n", encoding="utf-8")

    script_lines = [
        "// AUTO-GENERATED by PaintZ PackKit. DO NOT EDIT.",
        "class PaintZ_PaintCatalog",
        "{",
        "    static string GetFinishName(string paintCode)",
        "    {",
    ]
    for item in catalog:
        script_lines += [
            f'        if (paintCode == "{_enforce_string(item["code"])}")',
            f'            return "{_enforce_string(item["name"])}";',
        ]
    script_lines += ['        return "Original";', "    }", "", "    static bool HasPaintCode(string paintCode)", "    {"]
    for item in catalog:
        script_lines += [f'        if (paintCode == "{_enforce_string(item["code"])}")', "            return true;"]
    script_lines += ["        return false;", "    }", "", "    static bool IsPatternPaint(string paintCode)", "    {"]
    for item in catalog:
        if item.get("is_pattern"):
            script_lines += [f'        if (paintCode == "{_enforce_string(item["code"])}")', "            return true;"]
    script_lines += ["        return false;", "    }", "", "    static bool IsSupportedPatternScale(int scalePercent)", "    {"]
    for percent in supported_scale_percents:
        script_lines += [f"        if (scalePercent == {percent})", "            return true;"]
    script_lines += ["        return false;", "    }", "", "    static string GetPaintCodeByNetworkHash(int paintHash)", "    {"]
    for item in catalog:
        script_lines += [
            f'        if ("{_enforce_string(item["code"])}".Hash() == paintHash)',
            f'            return "{_enforce_string(item["code"])}";',
        ]
    script_lines += ['        return "";', "    }", "", "    static void GetPaintCodes(out array<string> paintCodes)", "    {", "        paintCodes = new array<string>;"]
    for item in catalog:
        script_lines.append(f'        paintCodes.Insert("{_enforce_string(item["code"])}");')
    script_lines += ["    }", "", "    static void GetCanTypes(out array<string> canTypes)", "    {", "        canTypes = new array<string>;"]
    for item in catalog:
        script_lines.append(f'        canTypes.Insert("{_enforce_string(_config_class(item, prefix))}");')
    script_lines += ["    }", "", "    static void RegisterActions(TTypenameArray actions)", "    {"]
    for item in catalog:
        script_lines.append(f"        actions.Insert({_action_class(item)});")
    script_lines += ["    }", "", "    static void AttachActionsToCan(PaintZ_SprayCanBase sprayCan)", "    {"]
    for item in catalog:
        script_lines.append(f"        sprayCan.AddAction({_action_class(item)});")
    script_lines += ["    }", "", "    static typename GetActionForPaint(string paintCode)", "    {"]
    for item in catalog:
        script_lines += [
            f'        if (paintCode == "{_enforce_string(item["code"])}")',
            f"            return {_action_class(item)};",
        ]
    script_lines += ["        typename noAction;", "        return noAction;", "    }", "};", ""]

    for item in catalog:
        script_lines += [
            f"class {_action_class(item)} : ActionPaintZPaintBase",
            "{",
            "    override string GetText()",
            "    {",
            f'        return "Paint {_enforce_string(item["name"])}";',
            "    }",
            "",
            "    override string GetPaintCode()",
            "    {",
            f'        return "{_enforce_string(item["code"])}";',
            "    }",
            "};",
            "",
        ]
    (out_dir / "PaintZ_PaintCatalog.generated.c").write_text("\n".join(script_lines), encoding="utf-8")

    nominal = int(dayz.get("types_nominal", 0))
    lifetime = int(dayz.get("types_lifetime", 14400))
    xml = ["<!-- AUTO-GENERATED by PaintZ PackKit. -->", "<types>"]
    for item in catalog:
        config_class = _config_class(item, prefix)
        xml += [
            f'  <type name="{escape(config_class)}">',
            f"    <nominal>{nominal}</nominal>",
            f"    <lifetime>{lifetime}</lifetime>",
            "    <restock>0</restock>",
            "    <min>0</min>",
            "    <quantmin>30</quantmin>",
            "    <quantmax>100</quantmax>",
            "    <cost>100</cost>",
            '    <flags count_in_cargo="0" count_in_hoarder="0" count_in_map="1" count_in_player="0" crafted="0" deloot="0"/>',
            "  </type>",
        ]
    xml.append("</types>")
    (out_dir / "types.generated.xml").write_text("\n".join(xml) + "\n", encoding="utf-8")
