from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from .ids import class_suffix, config_token


def _config_class(item: dict, prefix: str) -> str:
    return item.get("dayz_class") or prefix + class_suffix(item["name"], item["code"])


def _cpp_string(value: str) -> str:
    return value.replace('"', '\\"')


def _scale_percent(scale: float) -> int:
    percent = round(float(scale) * 100)
    if percent <= 0 or percent > 1000:
        raise ValueError(f"Invalid PaintZ pattern scale: {scale!r}")
    if abs(float(scale) - percent / 100.0) > 1e-9:
        raise ValueError(f"PaintZ pattern scale must resolve to a whole percentage: {scale!r}")
    return percent


def _owner_class(pack: dict, dayz: dict) -> str:
    explicit = dayz.get("owner_class")
    if explicit:
        return explicit
    identity = pack.get("author") or pack["name"]
    return f"{pack['prefix']}_{config_token(identity)}_{config_token(pack['name'])}"


def _patch_class(pack: dict, dayz: dict, owner_class: str) -> str:
    return dayz.get("patch_class") or f"{owner_class}_Patch"


def _addon_root(dayz: dict, owner_class: str) -> str:
    return dayz.get("addon_root") or owner_class


def _class_prefix(dayz: dict, owner_class: str) -> str:
    return dayz.get("class_prefix") or f"{owner_class}_SprayCan_"


def _finish_config_class(owner_class: str, item: dict) -> str:
    return f"{owner_class}_{item['type_code']}_{item['id']}"


def _surface_texture_path(surface_root: str, variant: dict) -> str:
    procedural = variant.get("procedural_texture")
    if procedural:
        return procedural
    return surface_root + "\\" + variant["texture_stem"] + "_co.paa"


def emit_dayz(
    catalog: list[dict],
    pack: dict,
    dayz: dict,
    out_dir: Path,
    *,
    official: bool = False,
):
    out_dir.mkdir(parents=True, exist_ok=True)
    if not dayz.get("emit_config_fragment", True):
        return

    owner_class = _owner_class(pack, dayz)
    patch_class = _patch_class(pack, dayz, owner_class)
    addon_root = _addon_root(dayz, owner_class)
    base_class = dayz.get("base_class", "PaintZ_SprayCanBase")
    class_prefix = _class_prefix(dayz, owner_class)
    can_root = addon_root + "\\data\\cans"
    surface_root = addon_root + "\\data\\surfaces"

    config_classes: set[str] = set()
    finish_classes: set[str] = set()
    for item in catalog:
        config_class = _config_class(item, class_prefix)
        finish_class = _finish_config_class(owner_class, item)
        if config_class in config_classes:
            raise ValueError(f"Duplicate generated DayZ classname: {config_class}")
        if finish_class in finish_classes:
            raise ValueError(f"Duplicate generated finish config classname: {finish_class}")
        config_classes.add(config_class)
        finish_classes.add(finish_class)

    lines = [
        "// AUTO-GENERATED by PaintZ PackKit. DO NOT EDIT.",
        "// Paint Pack API v1 standalone pack config.",
        "",
        "class CfgPatches",
        "{",
        f"    class {patch_class}",
        "    {",
        "        units[] =",
        "        {",
    ]
    for index, item in enumerate(catalog):
        comma = "," if index < len(catalog) - 1 else ""
        lines.append(f'            "{_config_class(item, class_prefix)}"{comma}')
    lines += [
        "        };",
        "        weapons[] = {};",
        "        requiredVersion = 0.1;",
        "        requiredAddons[] =",
        "        {",
        '            "PaintZ_DynamicPaint"',
        "        };",
        "    };",
        "};",
        "",
        "class CfgPaintZPacks",
        "{",
        f"    class {owner_class}",
        "    {",
        "        apiVersion = 1;",
        f'        prefix = "{_cpp_string(pack["prefix"])}";',
        f'        displayName = "{_cpp_string(pack["name"])}";',
    ]
    if official:
        lines.append("        official = 1;")
    lines += [
        "    };",
        "};",
        "",
        "class CfgPaintZFinishes",
        "{",
    ]

    for item in catalog:
        finish_class = _finish_config_class(owner_class, item)
        lines += [
            f"    class {finish_class}",
            "    {",
            f'        id = "{_cpp_string(item["code"])}";',
            f'        owner = "{_cpp_string(owner_class)}";',
            f'        displayName = "{_cpp_string(item["name"])}";',
            f'        type = "{_cpp_string(item["type"])}";',
        ]
        if item.get("is_pattern"):
            lines.append("        isPattern = 1;")
        lines += ["", "        class Surfaces", "        {"]
        for variant in item["surface_variants"]:
            percent = int(variant["scale_percent"])
            texture = _surface_texture_path(surface_root, variant)
            lines += [
                f"            class S{percent:03d}",
                "            {",
                f"                scalePercent = {percent};",
                f'                texture = "{_cpp_string(texture)}";',
                "            };",
            ]
        lines += ["        };", "    };", ""]

    lines += [
        "};",
        "",
        "class CfgVehicles",
        "{",
        f"    class {base_class};",
        "",
    ]
    for item in catalog:
        config_class = _config_class(item, class_prefix)
        can_texture = can_root + "\\" + item["texture_stem"] + "_co.paa"
        lines += [
            f"    class {config_class} : {base_class}",
            "    {",
            "        scope = 2;",
            f'        displayName = "PaintZ - {_cpp_string(item["name"])}";',
            f'        descriptionShort = "{_cpp_string(item["code"])} - PaintZ {_cpp_string(item["type"])} spray coating";',
            f'        paintzFinish = "{_cpp_string(item["code"])}";',
            f'        hiddenSelectionsTextures[] = {{"{_cpp_string(can_texture)}"}};',
            "    };",
            "",
        ]
    lines += ["};", ""]
    (out_dir / "config.cpp").write_text("\n".join(lines), encoding="utf-8")

    # Remove outputs from the legacy embedded-generator integration model so
    # a non-clean rebuild cannot accidentally ship stale per-finish scripts.
    for legacy_name in (
        "PaintZ_Paints.generated.inc",
        "PaintZ_Units.generated.inc",
        "PaintZ_PaintCatalog.generated.c",
    ):
        legacy_path = out_dir / legacy_name
        if legacy_path.exists():
            legacy_path.unlink()

    nominal = int(dayz.get("types_nominal", 0))
    lifetime = int(dayz.get("types_lifetime", 14400))
    xml = ["<!-- AUTO-GENERATED by PaintZ PackKit. -->", "<types>"]
    for item in catalog:
        config_class = _config_class(item, class_prefix)
        xml += [
            f'  <type name="{escape(config_class)}">',
            f"    <nominal>{nominal}</nominal>",
            f"    <lifetime>{lifetime}</lifetime>",
            "    <restock>0</restock>",
            "    <min>0</min>",
            "    <quantmin>30</quantmin>",
            "    <quantmax>100</quantmax>",
            "    <cost>100</cost>",
            '    <flags count_in_cargo="0" count_in_hoarder="0" count_in_map="1" count_in_player="0" crafted="0" deloot="0"/>',
            "  </type>",
        ]
    xml.append("</types>")
    (out_dir / "types.generated.xml").write_text("\n".join(xml) + "\n", encoding="utf-8")
